export const QUERY_GET_ARTICULOS = `
  SELECT
  FIRST 10
    ARTICULO_ID,
    NOMBRE,
    ESTATUS
  FROM ARTICULOS
`;

export const QUERY_GET_EXISTENCIAS = `
  SELECT
    PRECIO,
    EXIS.ARTICULO_ID,
    ARTICULOS.NOMBRE AS ARTICULO,
    EXISTENCIAS,
    ARTICULOS.LINEA_ARTICULO_ID,
    LINEAS_ARTICULOS.NOMBRE AS LINEA_ARTICULO
  FROM (
    SELECT
      SALDOS_IN.ARTICULO_ID,
      SUM(ENTRADAS_UNIDADES) - SUM(SALIDAS_UNIDADES) AS EXISTENCIAS
    FROM SALDOS_IN
    INNER JOIN ARTICULOS ON ARTICULOS.ARTICULO_ID = SALDOS_IN.ARTICULO_ID
    WHERE ALMACEN_ID = ?
    GROUP BY ARTICULO_ID
    ORDER BY ARTICULO_ID
  ) EXIS
  INNER JOIN ARTICULOS ON ARTICULOS.ARTICULO_ID = EXIS.ARTICULO_ID
  INNER JOIN PRECIOS_ARTICULOS ON PRECIOS_ARTICULOS.ARTICULO_ID = ARTICULOS.ARTICULO_ID
  INNER JOIN LINEAS_ARTICULOS ON LINEAS_ARTICULOS.LINEA_ARTICULO_ID = ARTICULOS.LINEA_ARTICULO_ID
  WHERE ESTATUS = ? AND PRECIO_EMPRESA_ID = 42
  ORDER BY EXISTENCIAS DESC
  ;
`;