export const QUERY_GET_ARTICULOS = `
  SELECT
  FIRST 10
    ARTICULO_ID,
    NOMBRE,
    ESTATUS
  FROM ARTICULOS
`;

// export const QUERY_GET_EXISTENCIAS = `
//   SELECT
//     PRECIO,
//     EXIS.ARTICULO_ID,
//     ARTICULOS.NOMBRE AS ARTICULO,
//     EXISTENCIAS,
//     ARTICULOS.LINEA_ARTICULO_ID,
//     LINEAS_ARTICULOS.NOMBRE AS LINEA_ARTICULO
//   FROM (
//     SELECT
//       SALDOS_IN.ARTICULO_ID,
//       SUM(ENTRADAS_UNIDADES) - SUM(SALIDAS_UNIDADES) AS EXISTENCIAS
//     FROM SALDOS_IN
//     INNER JOIN ARTICULOS ON ARTICULOS.ARTICULO_ID = SALDOS_IN.ARTICULO_ID
//     WHERE ALMACEN_ID = ?
//     GROUP BY ARTICULO_ID
//     ORDER BY ARTICULO_ID
//   ) EXIS
//   INNER JOIN ARTICULOS ON ARTICULOS.ARTICULO_ID = EXIS.ARTICULO_ID
//   INNER JOIN PRECIOS_ARTICULOS ON PRECIOS_ARTICULOS.ARTICULO_ID = ARTICULOS.ARTICULO_ID
//   INNER JOIN LINEAS_ARTICULOS ON LINEAS_ARTICULOS.LINEA_ARTICULO_ID = ARTICULOS.LINEA_ARTICULO_ID
//   WHERE ESTATUS = ? AND PRECIO_EMPRESA_ID = 42
//   ORDER BY EXISTENCIAS DESC
//   ;
// `;
export const QUERY_GET_EXISTENCIAS = `
SELECT
EXIS.ARTICULO_ID,
ARTICULOS.NOMBRE AS ARTICULO,
EXISTENCIAS,
ARTICULOS.LINEA_ARTICULO_ID,
LINEAS_ARTICULOS.NOMBRE AS LINEA_ARTICULO,
CAST(LIST(
  PRECIOS_EMPRESA.NOMBRE || ':' ||
  CAST(
    PRECIOS_ARTICULOS.PRECIO * (1 + COALESCE(IMP.TOTAL_PCTJE_IMPUESTO / 100, 0)) AS DECIMAL(12,2)
  )
) AS VARCHAR(500)) AS PRECIOS
FROM (
SELECT
  SALDOS_IN.ARTICULO_ID,
  SUM(ENTRADAS_UNIDADES) - SUM(SALIDAS_UNIDADES) AS EXISTENCIAS
FROM SALDOS_IN
WHERE ALMACEN_ID = ?
GROUP BY SALDOS_IN.ARTICULO_ID
) EXIS
INNER JOIN ARTICULOS ON ARTICULOS.ARTICULO_ID = EXIS.ARTICULO_ID
INNER JOIN LINEAS_ARTICULOS ON LINEAS_ARTICULOS.LINEA_ARTICULO_ID = ARTICULOS.LINEA_ARTICULO_ID
LEFT JOIN PRECIOS_ARTICULOS
ON PRECIOS_ARTICULOS.ARTICULO_ID = ARTICULOS.ARTICULO_ID
AND PRECIOS_ARTICULOS.PRECIO_EMPRESA_ID IN (42, 8437, 6925)
LEFT JOIN PRECIOS_EMPRESA
ON PRECIOS_EMPRESA.PRECIO_EMPRESA_ID = PRECIOS_ARTICULOS.PRECIO_EMPRESA_ID
LEFT JOIN (
  SELECT
    IA.ARTICULO_ID,
    SUM(I.PCTJE_IMPUESTO) AS TOTAL_PCTJE_IMPUESTO
  FROM IMPUESTOS_ARTICULOS IA
  INNER JOIN IMPUESTOS I ON I.IMPUESTO_ID = IA.IMPUESTO_ID
  GROUP BY IA.ARTICULO_ID
) IMP ON IMP.ARTICULO_ID = ARTICULOS.ARTICULO_ID
WHERE ARTICULOS.ESTATUS = ?
GROUP BY
EXIS.ARTICULO_ID,
ARTICULOS.NOMBRE,
EXISTENCIAS,
ARTICULOS.LINEA_ARTICULO_ID,
LINEAS_ARTICULOS.NOMBRE,
IMP.TOTAL_PCTJE_IMPUESTO
ORDER BY EXISTENCIAS DESC;
`;