// Queries para obtener el siguiente ID disponible
export const QUERY_GET_NEXT_DOCTO_IN_ID = `
  SELECT GEN_ID(GEN_DOCTOS_IN_ID, 1) AS NEXT_ID 
  FROM RDB$DATABASE
`;

export const QUERY_GET_NEXT_DOCTO_IN_DET_ID = `
  SELECT GEN_ID(GEN_DOCTOS_IN_DET_ID, 1) AS NEXT_ID 
  FROM RDB$DATABASE
`;

export const QUERY_GET_NEXT_SUB_MOVTO_ID = `
  SELECT GEN_ID(GEN_SUB_MOVTOS_IN_ID, 1) AS NEXT_ID 
  FROM RDB$DATABASE
`;

// Query para obtener el último folio con un prefijo específico
export const QUERY_GET_LAST_FOLIO_BY_PREFIX = `
  SELECT 
    FOLIO,
    CAST(SUBSTRING(FOLIO FROM 4) AS INTEGER) AS NUMERO_ACTUAL
  FROM DOCTOS_IN
  WHERE SUBSTRING(FOLIO FROM 1 FOR 3) = ?
    AND ALMACEN_ID = ?
    AND CONCEPTO_IN_ID = ?
    AND CHAR_LENGTH(FOLIO) = 9
  ORDER BY CAST(SUBSTRING(FOLIO FROM 4) AS INTEGER) DESC
  ROWS 1
`;

// Query para obtener el último prefijo usado en traspasos
export const QUERY_GET_LAST_PREFIX = `
  SELECT DISTINCT
    SUBSTRING(FOLIO FROM 1 FOR 3) AS PREFIJO
  FROM DOCTOS_IN
  WHERE FOLIO SIMILAR TO '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]'
    AND ALMACEN_ID = ?
    AND CONCEPTO_IN_ID = ?
  ORDER BY SUBSTRING(FOLIO FROM 1 FOR 3) DESC
  ROWS 1
`;

// Query para insertar encabezado de traspaso
export const QUERY_INSERT_DOCTO_IN = `
  INSERT INTO DOCTOS_IN (
    DOCTO_IN_ID, ALMACEN_ID, CONCEPTO_IN_ID, SUCURSAL_ID, 
    FOLIO, NATURALEZA_CONCEPTO, FECHA, ALMACEN_DESTINO_ID, 
    CENTRO_COSTO_ID, CANCELADO, APLICADO, DESCRIPCION, 
    CUENTA_CONCEPTO, FORMA_EMITIDA, CONTABILIZADO, SISTEMA_ORIGEN, 
    USUARIO_CREADOR, FECHA_HORA_CREACION, USUARIO_AUT_CREACION, 
    USUARIO_ULT_MODIF, FECHA_HORA_ULT_MODIF, USUARIO_AUT_MODIF,
    USUARIO_CANCELACION, FECHA_HORA_CANCELACION, USUARIO_AUT_CANCELACION
  ) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
  )
  RETURNING DOCTO_IN_ID
`;

// Query para insertar detalle de traspaso
export const QUERY_INSERT_DOCTO_IN_DET = `
  INSERT INTO DOCTOS_IN_DET (
    DOCTO_IN_DET_ID, DOCTO_IN_ID, ALMACEN_ID, CONCEPTO_IN_ID, 
    CLAVE_ARTICULO, ARTICULO_ID, TIPO_MOVTO, UNIDADES, 
    COSTO_UNITARIO, COSTO_TOTAL, METODO_COSTEO, CANCELADO, 
    APLICADO, COSTEO_PEND, PEDIMENTO_PEND, ROL, FECHA, CENTRO_COSTO_ID
  ) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
  )
  RETURNING DOCTO_IN_DET_ID
`;

// Query para insertar sub movimiento
export const QUERY_INSERT_SUB_MOVTO = `
  INSERT INTO SUB_MOVTOS_IN (DOCTO_IN_DET_ID, SUB_MOVTO_ID) 
  VALUES (?, ?)
`;

// Stored procedure para aplicar documento
export const QUERY_APLICA_DOCTO = `
  EXECUTE PROCEDURE aplica_docto_in(?)
`;

// Query para obtener traspasos
export const QUERY_GET_TRASPASOS = `
  SELECT 
    D.DOCTO_IN_ID,
    D.ALMACEN_ID,
    D.ALMACEN_DESTINO_ID,
    D.FOLIO,
    D.FECHA,
    D.DESCRIPCION,
    D.APLICADO,
    D.CANCELADO,
    D.USUARIO_CREADOR,
    D.FECHA_HORA_CREACION,
    A1.NOMBRE AS ALMACEN_ORIGEN,
    A2.NOMBRE AS ALMACEN_DESTINO
  FROM DOCTOS_IN D
  LEFT JOIN ALMACENES A1 ON A1.ALMACEN_ID = D.ALMACEN_ID
  LEFT JOIN ALMACENES A2 ON A2.ALMACEN_ID = D.ALMACEN_DESTINO_ID
  WHERE D.CONCEPTO_IN_ID = 36
    AND D.ALMACEN_DESTINO_ID IS NOT NULL
    AND D.FOLIO SIMILAR TO '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]'
  ORDER BY D.FECHA DESC, D.DOCTO_IN_ID DESC
`;

// Query para obtener detalle de un traspaso
export const QUERY_GET_TRASPASO_DETALLE = `
  SELECT 
    DET.DOCTO_IN_DET_ID,
    DET.ARTICULO_ID,
    DET.CLAVE_ARTICULO,
    DET.TIPO_MOVTO,
    DET.UNIDADES,
    DET.COSTO_UNITARIO,
    DET.COSTO_TOTAL,
    DET.ALMACEN_ID,
    DET.ROL,
    ART.NOMBRE AS ARTICULO_NOMBRE
  FROM DOCTOS_IN_DET DET
  LEFT JOIN ARTICULOS ART ON ART.ARTICULO_ID = DET.ARTICULO_ID
  WHERE DET.DOCTO_IN_ID = ?
  ORDER BY DET.DOCTO_IN_DET_ID
`;

// Query para obtener costo promedio de un artículo
export const QUERY_GET_COSTO_ARTICULO = `
  SELECT 
    COALESCE(CP.COSTO_PROM, 0) AS COSTO_UNITARIO
  FROM ARTICULOS A
  LEFT JOIN COSTOS_PROMEDIOS CP ON CP.ARTICULO_ID = A.ARTICULO_ID 
    AND CP.ALMACEN_ID = ?
  WHERE A.ARTICULO_ID = ?
`;

// Query para validar existencias antes del traspaso
export const QUERY_VALIDAR_EXISTENCIAS = `
  SELECT 
    A.ARTICULO_ID,
    A.CLAVE,
    A.NOMBRE,
    COALESCE(EA.EXISTENCIA, 0) AS EXISTENCIA,
    COALESCE(EA.EXISTENCIA, 0) AS EXISTENCIA_DISPONIBLE
  FROM ARTICULOS A
  LEFT JOIN EXIST_ALMACEN EA ON EA.ARTICULO_ID = A.ARTICULO_ID 
    AND EA.ALMACEN_ID = ?
  WHERE A.ARTICULO_ID = ?
`;