export const QUERY_GET_ALMACENES: string = `
  SELECT
  ALMACENES.ALMACEN_ID,
  ALMACENES.NOMBRE AS ALMACEN,
  COALESCE(EXIS.EXISTENCIAS, 0) AS EXISTENCIAS
  FROM ALMACENES
  LEFT JOIN (
    SELECT
      SALDOS_IN.ALMACEN_ID,
      SUM(ENTRADAS_UNIDADES) - SUM(SALIDAS_UNIDADES) AS EXISTENCIAS
    FROM SALDOS_IN
    GROUP BY ALMACEN_ID
  ) EXIS ON ALMACENES.ALMACEN_ID = EXIS.ALMACEN_ID
  WHERE ALMACENES.OCULTO = 'N'
  ORDER BY EXISTENCIAS DESC
`;

export const QUERY_GET_ALMACEN_BY_ID = `
  SELECT
  ALMACENES.ALMACEN_ID,
  ALMACENES.NOMBRE AS ALMACEN,
  COALESCE(EXIS.EXISTENCIAS, 0) AS EXISTENCIAS
  FROM ALMACENES
  LEFT JOIN (
    SELECT
      SALDOS_IN.ALMACEN_ID,
      SUM(ENTRADAS_UNIDADES) - SUM(SALIDAS_UNIDADES) AS EXISTENCIAS
    FROM SALDOS_IN
    GROUP BY ALMACEN_ID
  ) EXIS ON ALMACENES.ALMACEN_ID = EXIS.ALMACEN_ID
  WHERE ALMACENES.OCULTO = 'N' AND ALMACENES.ALMACEN_ID = ?
`;

export const QUERY_GET_ALMACEN_EXISTENCIAS_BY_ID: string = `
  SELECT
  ALMACENES.ALMACEN_ID,
  ALMACENES.NOMBRE AS ALMACEN,
  COALESCE(EXIS.EXISTENCIAS, 0) AS EXISTENCIAS
  FROM ALMACENES
  LEFT JOIN (
    SELECT
      SALDOS_IN.ALMACEN_ID,
      SUM(ENTRADAS_UNIDADES) - SUM(SALIDAS_UNIDADES) AS EXISTENCIAS
    FROM SALDOS_IN
    GROUP BY ALMACEN_ID
  ) EXIS ON ALMACENES.ALMACEN_ID = EXIS.ALMACEN_ID
  WHERE ALMACENES.OCULTO = 'N' AND ALMACENES.ALMACEN_ID = ?
  ORDER BY EXISTENCIAS DESC
`;

export const QUERY_GET_ALMACENES_BY_ID: string = `
  SELECT
  EXIS.ARTICULO_ID,
  ARTICULOS.NOMBRE AS ARTICULO,
  EXISTENCIAS,
  ARTICULOS.LINEA_ARTICULO_ID,
  LINEAS_ARTICULOS.NOMBRE AS LINEA_ARTICULO,
  CAST(LIST(PRECIOS_EMPRESA.NOMBRE || ':' || PRECIOS_ARTICULOS.PRECIO) AS VARCHAR(500)) AS PRECIOS
  FROM
  (
    SELECT
      ARTICULO_ID,
      SUM(ENTRADAS_UNIDADES) - SUM(SALIDAS_UNIDADES) AS EXISTENCIAS
    FROM SALDOS_IN
    WHERE ALMACEN_ID = ?
    GROUP BY ARTICULO_ID
    ORDER BY EXISTENCIAS DESC
  ) EXIS
  INNER JOIN ARTICULOS ON ARTICULOS.ARTICULO_ID = EXIS.ARTICULO_ID
  INNER JOIN LINEAS_ARTICULOS ON LINEAS_ARTICULOS.LINEA_ARTICULO_ID = ARTICULOS.LINEA_ARTICULO_ID
  LEFT JOIN PRECIOS_ARTICULOS 
  ON PRECIOS_ARTICULOS.ARTICULO_ID = ARTICULOS.ARTICULO_ID 
  AND PRECIOS_ARTICULOS.PRECIO_EMPRESA_ID IN (42, 8437, 6925)
  LEFT JOIN PRECIOS_EMPRESA 
  ON PRECIOS_EMPRESA.PRECIO_EMPRESA_ID = PRECIOS_ARTICULOS.PRECIO_EMPRESA_ID
  WHERE EXISTENCIAS > 0 AND ARTICULOS.NOMBRE CONTAINING ?
  GROUP BY
  EXIS.ARTICULO_ID,
  ARTICULOS.NOMBRE,
  EXISTENCIAS,
  ARTICULOS.LINEA_ARTICULO_ID,
  LINEAS_ARTICULOS.NOMBRE
  ORDER BY ARTICULO
  ;
`;