export const QUERY_GET_RUTAS = `
  SELECT
    COBRADORES.COBRADOR_ID,
    COBRADORES.NOMBRE AS COBRADOR
  FROM
    COBRADORES
`;

export const QUERY_GET_CTAS_POR_RUTAS = `
  SELECT
  N.COBRADOR_ID,
  COUNT(N.DOCTO_CC_ACR_ID) AS TOTAL_CUENTAS
  FROM
  (
  SELECT
      M.DOCTO_CC_ACR_ID,
      DOCTOS_CC.DOCTO_CC_ID,
      DOCTOS_CC.FOLIO,
      DOCTOS_CC.CLIENTE_ID,
    DOCTOS_CC.APLICADO,
      CLIENTES.NOMBRE AS CLIENTE,
    CLIENTES.COBRADOR_ID,
      M.IMPORTE_PAGO_PROMEDIO,
      M.TOTAL_IMPORTE,
      M.NUM_IMPORTES,
      DOCTOS_CC.FECHA,
      LIBRES_CARGOS_CC.PARCIALIDAD,
      LIBRES_CARGOS_CC.ENGANCHE,
      IMPORTES_DOCTOS_CC.IMPORTE + IMPORTES_DOCTOS_CC.IMPUESTO AS PRECIO_TOTAL,
      M.IMPTE_REST,
      IMPORTES_DOCTOS_CC.IMPORTE + IMPORTES_DOCTOS_CC.IMPUESTO - M.TOTAL_IMPORTE - M.IMPTE_REST AS SALDO_REST,
      M.FECHA_ULT_PAGO
    FROM
    (
      SELECT
        IMPORTES_DOCTOS_CC.DOCTO_CC_ACR_ID,
        SUM(CASE WHEN DOCTOS_CC.CONCEPTO_CC_ID IN (87327, 155) THEN (IMPORTES_DOCTOS_CC.IMPORTE + IMPORTES_DOCTOS_CC.IMPUESTO) ELSE 0 END) AS TOTAL_IMPORTE,
        AVG(CASE WHEN DOCTOS_CC.CONCEPTO_CC_ID IN (87327, 155) THEN (IMPORTES_DOCTOS_CC.IMPORTE + IMPORTES_DOCTOS_CC.IMPUESTO) ELSE NULL END) AS IMPORTE_PAGO_PROMEDIO,
        COUNT(CASE WHEN DOCTOS_CC.CONCEPTO_CC_ID IN (87327, 155) THEN (IMPORTES_DOCTOS_CC.IMPORTE + IMPORTES_DOCTOS_CC.IMPUESTO) ELSE NULL END) AS NUM_IMPORTES,
        SUM(CASE WHEN DOCTOS_CC.CONCEPTO_CC_ID NOT IN (5, 87327, 155) THEN (IMPORTES_DOCTOS_CC.IMPORTE + IMPORTES_DOCTOS_CC.IMPUESTO) ELSE 0 END) AS IMPTE_REST,
        MAX(CASE WHEN DOCTOS_CC.CONCEPTO_CC_ID IN (87327, 155) THEN DOCTOS_CC.FECHA ELSE NULL END) AS FECHA_ULT_PAGO
      FROM
        DOCTOS_CC
      INNER JOIN IMPORTES_DOCTOS_CC ON IMPORTES_DOCTOS_CC.DOCTO_CC_ID = DOCTOS_CC.DOCTO_CC_ID
    INNER JOIN CLIENTES ON CLIENTES.CLIENTE_ID = DOCTOS_CC.CLIENTE_ID
      WHERE DOCTOS_CC.CANCELADO = 'N'
      GROUP BY IMPORTES_DOCTOS_CC.DOCTO_CC_ACR_ID
    ) M
    INNER JOIN DOCTOS_CC ON DOCTOS_CC.DOCTO_CC_ID = M.DOCTO_CC_ACR_ID
    INNER JOIN CLIENTES ON CLIENTES.CLIENTE_ID = DOCTOS_CC.CLIENTE_ID
    INNER JOIN LIBRES_CARGOS_CC ON LIBRES_CARGOS_CC.DOCTO_CC_ID = DOCTOS_CC.DOCTO_CC_ID
    INNER JOIN IMPORTES_DOCTOS_CC ON IMPORTES_DOCTOS_CC.DOCTO_CC_ID = DOCTOS_CC.DOCTO_CC_ID
    WHERE
      DOCTOS_CC.CANCELADO = 'N'
      AND (
        IMPORTES_DOCTOS_CC.IMPORTE + IMPORTES_DOCTOS_CC.IMPUESTO - M.TOTAL_IMPORTE - M.IMPTE_REST > 0
        OR (M.FECHA_ULT_PAGO >= ? AND M.FECHA_ULT_PAGO <= ?)
      )
      AND DOCTOS_CC.FECHA < ?
  ) AS N
  GROUP BY N.COBRADOR_ID
`;
