const QUERY_BASE_GET_MOVIMIENTOS = `
  SELECT
  FIRST ?
    DOCTOS_IN.DOCTO_IN_ID,
    DOCTOS_IN.ALMACEN_ID,
    ALMACENES.NOMBRE AS ALMACEN,
    DOCTOS_IN.CONCEPTO_IN_ID,
    CONCEPTOS_IN.NOMBRE AS CONCEPTO,
    DOCTOS_IN.DESCRIPCION,
    DOCTOS_IN.USUARIO_ULT_MODIF,
    DOCTOS_IN.FOLIO,
    DOCTOS_IN.FECHA
  FROM DOCTOS_IN
  INNER JOIN ALMACENES ON ALMACENES.ALMACEN_ID = DOCTOS_IN.ALMACEN_ID
  INNER JOIN CONCEPTOS_IN ON CONCEPTOS_IN.CONCEPTO_IN_ID = DOCTOS_IN.CONCEPTO_IN_ID
`;

const ORDER_BASE_GET_MOVIMIENTOS = `
  ORDER BY FECHA DESC;
`;

export const QUERY_GET_MOVIMIENTOS = `
  ${QUERY_BASE_GET_MOVIMIENTOS}
  ${ORDER_BASE_GET_MOVIMIENTOS}
`;

export const QUERY_GET_MOVIMIENTOS_BY_ALMACEN_ID = `
  ${QUERY_BASE_GET_MOVIMIENTOS}
  WHERE DOCTOS_IN.ALMACEN_ID = ?
  ${ORDER_BASE_GET_MOVIMIENTOS}
`;