export const SET_VISITA = `
    INSERT INTO MSP_VISITAS (
        ID,
        CLIENTE_ID,
        COBRADOR, 
        COBRADOR_ID, 
        FECHA, 
        FORMA_COBRO_ID, 
        LAT, 
        LNG, 
        NOTA, 
        TIPO_VISITA, 
        ZONA_CLIENTE_ID,
        IMPTE_DOCTO_CC_ID
    ) 
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`;

export const GET_VISITAS_BY_DATE_AND_ZONA_CLIENTE_ID = `
    SELECT
        ID,
        CLIENTE_ID,
        COBRADOR,
        COBRADOR_ID,
        FECHA,
        FORMA_COBRO_ID,
        LAT,
        LNG,
        NOTA,
        TIPO_VISITA,
        ZONA_CLIENTE_ID
    FROM MSP_VISITAS
    WHERE FECHA BETWEEN ? AND ?
    AND ZONA_CLIENTE_ID = ?
`;

export const GET_VISITAS_BY_ID = `
    SELECT
        ID,
        CLIENTE_ID,
        COBRADOR,
        COBRADOR_ID,
        FECHA,
        FORMA_COBRO_ID,
        LAT,
        LNG,
        NOTA,
        TIPO_VISITA,
        ZONA_CLIENTE_ID
    FROM MSP_VISITAS
    WHERE ID = ?
`;

export const GET_PAGOS_AND_VISITAS_BY_FECHA = (dateInit: string, dateEnd: string, zonaClienteId: number) => `
    SELECT
        MSP_VISITAS.ID,
        COBRADOR, MSP_VISITAS.COBRADOR_ID, MSP_VISITAS.FECHA, MSP_VISITAS.FORMA_COBRO_ID, 0 as IMPORTE, MSP_VISITAS.LAT,
        MSP_VISITAS.LNG, NOTA,
        TIPO_VISITA, CLIENTES.NOMBRE AS CLIENTE, MSP_VISITAS.ZONA_CLIENTE_ID, MSP_VISITAS.CLIENTE_ID, 'VISITA' AS TIPO,
        COALESCE(MSP_VISITAS.IMPTE_DOCTO_CC_ID, 0) AS VENTA_ID
    FROM
        MSP_VISITAS
    INNER JOIN CLIENTES ON CLIENTES.CLIENTE_ID = MSP_VISITAS.CLIENTE_ID
        WHERE MSP_VISITAS.ZONA_CLIENTE_ID = ${zonaClienteId}
        AND MSP_VISITAS.FECHA BETWEEN '${dateInit}' AND '${dateEnd}'
    UNION ALL
    SELECT
        CAST(DOCTOS_CC.DOCTO_CC_ID AS VARCHAR(10)) AS ID,
        COBRADORES.NOMBRE AS COBRADOR,
        COBRADORES.COBRADOR_ID,
        MSP_PAGOS_RECIBIDOS.FECHA AS FECHA,
        FORMAS_COBRO_DOCTOS.FORMA_COBRO_ID,
        IMPORTES_DOCTOS_CC.IMPORTE + IMPORTES_DOCTOS_CC.IMPUESTO AS IMPORTE,
        DOCTOS_CC.LAT,
        DOCTOS_CC.LON AS LNG,
        '' AS NOTA,
        '' AS TIPO_VISITA,
        CLIENTES.NOMBRE AS CLIENTE,
        CLIENTES.ZONA_CLIENTE_ID,
        CLIENTES.CLIENTE_ID,
        'PAGO' AS TIPO,
        DOCTOS_CC.DOCTO_CC_ID AS VENTA_ID
    FROM
        DOCTOS_CC
        INNER JOIN IMPORTES_DOCTOS_CC ON IMPORTES_DOCTOS_CC.DOCTO_CC_ID = DOCTOS_CC.DOCTO_CC_ID
        INNER JOIN CLIENTES ON CLIENTES.CLIENTE_ID = DOCTOS_CC.CLIENTE_ID
        INNER JOIN COBRADORES ON COBRADORES.COBRADOR_ID = CLIENTES.COBRADOR_ID
        INNER JOIN FORMAS_COBRO_DOCTOS ON FORMAS_COBRO_DOCTOS.DOCTO_ID = DOCTOS_CC.DOCTO_CC_ID
        LEFT JOIN MSP_PAGOS_RECIBIDOS ON DOCTOS_CC.DOCTO_CC_ID = MSP_PAGOS_RECIBIDOS.DOCTO_CC_ID
    WHERE
        DOCTOS_CC.CANCELADO = 'N'
        AND DOCTOS_CC.CONCEPTO_CC_ID IN (87327, 27969)
        AND CLIENTES.ZONA_CLIENTE_ID = ${zonaClienteId}
        AND MSP_PAGOS_RECIBIDOS.FECHA >= TIMESTAMP '${dateInit}' AND MSP_PAGOS_RECIBIDOS.FECHA <= TIMESTAMP '${dateEnd}';
`