export const QUERY_GET_MOVIMIENTO_INDIV = `
  SELECT
    DOCTO_IN_DET_ID,
    DOCTO_IN_ID,
    ALMACEN_ID,
    CONCEPTOS_IN.CONCEPTO_IN_ID,
    CONCEPTOS_IN.NOMBRE AS CONCEPTO,
    CLAVE_ARTICULO,
    ARTICULOS.ARTICULO_ID,
    ARTICULOS.NOMBRE AS ARTICULO,
    TIPO_MOVTO,
    UNIDADES,
    COSTO_UNITARIO, 
	  COSTO_TOTAL,
    CANCELADO,
    APLICADO,
    COSTEO_PEND,
    PEDIMENTO_PEND,
    ROL,
    FECHA,
    CENTRO_COSTO_ID
  FROM DOCTOS_IN_DET
  INNER JOIN ARTICULOS ON ARTICULOS.ARTICULO_ID = DOCTOS_IN_DET.ARTICULO_ID
  INNER JOIN CONCEPTOS_IN ON CONCEPTOS_IN.CONCEPTO_IN_ID = DOCTOS_IN_DET.CONCEPTO_IN_ID
  WHERE ALMACEN_ID = ? AND DOCTO_IN_ID IN
`;