-- Garantías extras sin venta asociada
-- Agrega campos NOMBRE_CLIENTE y NOMBRE_PRODUCTO para garantías sin DOCTO_CC_ID

ALTER TABLE MSP_GARANTIAS ADD NOMBRE_CLIENTE VARCHAR(200);
ALTER TABLE MSP_GARANTIAS ADD NOMBRE_PRODUCTO VARCHAR(200);

-- DOCTO_CC_ID tiene NOT NULL, quitarlo para permitir garantías extras sin venta
ALTER TABLE MSP_GARANTIAS ALTER COLUMN DOCTO_CC_ID DROP NOT NULL;

COMMIT;
