const QUERY_GET_CLIENTE_BASE = `
  SELECT
    CLIENTES.CLIENTE_ID,
    CLIENTES.NOMBRE,
    DIRS_CLIENTES.DIR_CLI_ID,
    DIRS_CLIENTES.CALLE || ', ' || CIUDADES.NOMBRE || ', ' || ESTADOS.NOMBRE AS DIRECCION,
    CLIENTES.LIMITE_CREDITO,
    CLIENTES.ZONA_CLIENTE_ID,
    DIRS_CLIENTES.TELEFONO1 AS TELEFONO,
    ZONAS_CLIENTES.NOMBRE AS ZONA,
    CLIENTES.NOTAS,
    CLIENTES.COBRADOR_ID,
    COBRADORES.NOMBRE AS COBRADOR,
    CLIENTES.ESTATUS
  FROM CLIENTES
  INNER JOIN ZONAS_CLIENTES ON ZONAS_CLIENTES.ZONA_CLIENTE_ID = CLIENTES.ZONA_CLIENTE_ID
  INNER JOIN DIRS_CLIENTES ON DIRS_CLIENTES.CLIENTE_ID = CLIENTES.CLIENTE_ID
  INNER JOIN CIUDADES ON CIUDADES.CIUDAD_ID = DIRS_CLIENTES.CIUDAD_ID
  INNER JOIN ESTADOS ON ESTADOS.ESTADO_ID = DIRS_CLIENTES.ESTADO_ID
  INNER JOIN COBRADORES ON COBRADORES.COBRADOR_ID = CLIENTES.COBRADOR_ID
`;

export const QUERY_GET_CLIENTE_BY_ID = `
${QUERY_GET_CLIENTE_BASE}
  WHERE CLIENTES.CLIENTE_ID = ?
`;

export const QUERY_GET_CLIENTE_BY_TEXT = `
  SELECT
  FIRST 50
    CLIENTES.CLIENTE_ID,
    CLIENTES.NOMBRE,
    DIRS_CLIENTES.DIR_CLI_ID,
    DIRS_CLIENTES.CALLE || CIUDADES.NOMBRE || ESTADOS.NOMBRE AS DIRECCION,
    CLIENTES.LIMITE_CREDITO,
    CLIENTES.ZONA_CLIENTE_ID,
    DIRS_CLIENTES.TELEFONO1 AS TELEFONO,
    ZONAS_CLIENTES.NOMBRE AS ZONA,
    CLIENTES.NOTAS,
    CLIENTES.COBRADOR_ID,
    COBRADORES.NOMBRE AS COBRADOR,
    CLIENTES.ESTATUS
  FROM CLIENTES
  INNER JOIN ZONAS_CLIENTES ON ZONAS_CLIENTES.ZONA_CLIENTE_ID = CLIENTES.ZONA_CLIENTE_ID
  INNER JOIN DIRS_CLIENTES ON DIRS_CLIENTES.CLIENTE_ID = CLIENTES.CLIENTE_ID
  INNER JOIN CIUDADES ON CIUDADES.CIUDAD_ID = DIRS_CLIENTES.CIUDAD_ID
  INNER JOIN ESTADOS ON ESTADOS.ESTADO_ID = DIRS_CLIENTES.ESTADO_ID
  INNER JOIN COBRADORES ON COBRADORES.COBRADOR_ID = CLIENTES.COBRADOR_ID
  WHERE CLIENTES.NOMBRE CONTAINING ? ORDER BY CLIENTES.NOMBRE
  `;

export const QUERY_GET_CLIENTE_BY_RUTA = `
  SELECT
    CLIENTES.CLIENTE_ID
  FROM CLIENTES
  WHERE CLIENTES.ESTATUS = 'A' AND CLIENTES.COBRADOR_ID = ?
`;
