export const GET_ZONAS_CLIENTE = `
  SELECT
    ZONA_CLIENTE_ID, NOMBRE AS ZONA_CLIENTE
  FROM
    ZONAS_CLIENTES
  ORDER BY NOMBRE;
`;

export const GET_COBRADORES_POR_ZONA = `
  SELECT
    ZONA_CLIENTE_ID,
    COBRADOR_ID,
    COBRADOR
  FROM (
    SELECT
      CL.ZONA_CLIENTE_ID,
      C.COBRADOR_ID,
      C.NOMBRE AS COBRADOR,
      COUNT(*) AS TOTAL_CLIENTES,
      ROW_NUMBER() OVER (PARTITION BY CL.ZONA_CLIENTE_ID ORDER BY COUNT(*) DESC) AS RN
    FROM CLIENTES CL
    INNER JOIN COBRADORES C ON C.COBRADOR_ID = CL.COBRADOR_ID
    WHERE CL.ZONA_CLIENTE_ID IS NOT NULL
    GROUP BY CL.ZONA_CLIENTE_ID, C.COBRADOR_ID, C.NOMBRE
  )
  WHERE RN = 1
  ORDER BY ZONA_CLIENTE_ID
`;
