export const GET_ZONAS_CLIENTE = `
  SELECT
    ZONA_CLIENTE_ID, NOMBRE AS ZONA_CLIENTE
  FROM
    ZONAS_CLIENTES;
`;

export const GET_COBRADORES_POR_ZONA = `
  SELECT DISTINCT
    CL.ZONA_CLIENTE_ID,
    C.COBRADOR_ID,
    C.NOMBRE AS COBRADOR
  FROM CLIENTES CL
  INNER JOIN COBRADORES C ON C.COBRADOR_ID = CL.COBRADOR_ID
  WHERE CL.ZONA_CLIENTE_ID IS NOT NULL
  ORDER BY CL.ZONA_CLIENTE_ID, C.NOMBRE
`;
