-- Script para crear la tabla de combos de ventas locales
-- y agregar el campo COMBO_ID a la tabla de productos

-- 1. Crear tabla MSP_LOCAL_SALE_COMBO
CREATE TABLE MSP_LOCAL_SALE_COMBO (
    COMBO_ID VARCHAR(100) NOT NULL,
    LOCAL_SALE_ID VARCHAR(100) NOT NULL,
    NOMBRE_COMBO VARCHAR(200) NOT NULL,
    PRECIO_LISTA DECIMAL(15,2) DEFAULT 0,
    PRECIO_CORTO_PLAZO DECIMAL(15,2) DEFAULT 0,
    PRECIO_CONTADO DECIMAL(15,2) DEFAULT 0,
    PRIMARY KEY (COMBO_ID),
    FOREIGN KEY (LOCAL_SALE_ID) REFERENCES MSP_LOCAL_SALE(LOCAL_SALE_ID) ON DELETE CASCADE
);

-- 2. Agregar campo COMBO_ID a la tabla de productos (nullable)
ALTER TABLE MSP_LOCAL_SALE_PRODUCT ADD COMBO_ID VARCHAR(100);

-- 3. Crear índice para mejorar consultas por LOCAL_SALE_ID en combos
CREATE INDEX IDX_COMBO_LOCAL_SALE ON MSP_LOCAL_SALE_COMBO(LOCAL_SALE_ID);

-- 4. Crear índice para mejorar consultas por COMBO_ID en productos
CREATE INDEX IDX_PRODUCT_COMBO ON MSP_LOCAL_SALE_PRODUCT(COMBO_ID);
